/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    NameRegistry: {
      address:
        "0x35fd37dabd9dd5860cd4bfaa8a2624988fb03b3ccb09219af77337888ba212d",
      abi: [
        {
          type: "impl",
          name: "NameRegistry",
          interface_name: "contracts::NameRegistry::INameRegistry",
        },
        {
          type: "enum",
          name: "contracts::NameRegistry::NameRegistry::RegistrationType",
          variants: [
            {
              name: "Finite",
              type: "core::integer::u64",
            },
            {
              name: "Infinite",
              type: "()",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::NameRegistry::NameRegistry::Person",
          members: [
            {
              name: "address",
              type: "core::starknet::contract_address::ContractAddress",
            },
            {
              name: "name",
              type: "core::felt252",
            },
          ],
        },
        {
          type: "struct",
          name: "contracts::NameRegistry::NameRegistry::RegistrationInfo",
          members: [
            {
              name: "name",
              type: "core::felt252",
            },
            {
              name: "registration_type",
              type: "contracts::NameRegistry::NameRegistry::RegistrationType",
            },
            {
              name: "registration_date",
              type: "core::integer::u64",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::NameRegistry::INameRegistry",
          items: [
            {
              type: "function",
              name: "store_name",
              inputs: [
                {
                  name: "name",
                  type: "core::felt252",
                },
                {
                  name: "registration_type",
                  type: "contracts::NameRegistry::NameRegistry::RegistrationType",
                },
              ],
              outputs: [],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "get_name",
              inputs: [
                {
                  name: "address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_owner",
              inputs: [],
              outputs: [
                {
                  type: "contracts::NameRegistry::NameRegistry::Person",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_owner_name",
              inputs: [],
              outputs: [
                {
                  type: "core::felt252",
                },
              ],
              state_mutability: "view",
            },
            {
              type: "function",
              name: "get_registration_info",
              inputs: [
                {
                  name: "address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "contracts::NameRegistry::NameRegistry::RegistrationInfo",
                },
              ],
              state_mutability: "view",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "owner",
              type: "contracts::NameRegistry::NameRegistry::Person",
            },
          ],
        },
        {
          type: "function",
          name: "get_contract_name",
          inputs: [],
          outputs: [
            {
              type: "core::felt252",
            },
          ],
          state_mutability: "view",
        },
        {
          type: "event",
          name: "contracts::NameRegistry::NameRegistry::StoredName",
          kind: "struct",
          members: [
            {
              name: "user",
              type: "core::starknet::contract_address::ContractAddress",
              kind: "key",
            },
            {
              name: "name",
              type: "core::felt252",
              kind: "data",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::NameRegistry::NameRegistry::Event",
          kind: "enum",
          variants: [
            {
              name: "StoredName",
              type: "contracts::NameRegistry::NameRegistry::StoredName",
              kind: "nested",
            },
          ],
        },
      ],
      classHash:
        "0x2a13a7f4aa9911b979ee23604d6a4a650993f79ec1acc6a1a5ba7cfc1409144",
    },
  },
} as const;

export default deployedContracts;
